### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by ligi**

### CODE REVIEW

**Comment by AlexanderPrendota** [comment]
Thanks!

**Comment by ligi** [comment]
you are very welcome. Can I use this opportunity to ask one question: https://stackoverflow.com/questions/56453818/unable-to-resolve-version-for-dependency-org-jetbrains-kotlinkotlin-testjar

**Comment by AlexanderPrendota** [comment]
Yes, sure! You are welcome! =)

**Comment by AlexanderPrendota** [comment]
I can take a look at your question after 13 June :( Sorry! 
You wanna add 
```
library "com.github.komputing.kethereum:model:0.75.1"
+    library "com.github.komputing.kethereum:erc55:0.75.1"
``` right?

**Pull request merged**
