### PR TITLE
Fix KT-25891 by passing encoding parameter

### PR DESCRIPTION
**Pull request by ligi**

### CODE REVIEW

**Comment by AlexanderPrendota** [comment]
Hello! @ligi 
Does this fix help you with KT-25891 on Ubuntu?

**Comment by ligi** [comment]
yes - this seems to solve this particular error - unfortunately I get a new one then - but seems to me I am one error further down to getting it run:

```
frontend_1  |  java.sql.SQLException: Cannot create PoolableConnectionFactory (Unable to load authentication plugin 'caching_sha2_password'.)
frontend_1  | 	at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:2346)
frontend_1  | 	at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:2072)
frontend_1  | 	at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:1525)
frontend_1  | 	at org.jetbrains.webdemo.database.MySqlConnector.<init>(MySqlConnector.java:59)
frontend_1  | 	at org.jetbrains.webdemo.database.MySqlConnector.<clinit>(MySqlConnector.java:48)
frontend_1  | 	at org.jetbrains.webdemo.servlet.KotlinHttpServlet.init(KotlinHttpServlet.java:68)
frontend_1  | 	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1144)
frontend_1  | 	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1091)
frontend_1  | 	at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:773)
frontend_1  | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:133)
frontend_1  | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
frontend_1  | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
frontend_1  | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
frontend_1  | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
frontend_1  | 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
frontend_1  | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
frontend_1  | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
frontend_1  | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
frontend_1  | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
frontend_1  | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800)
frontend_1  | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471)
frontend_1  | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
frontend_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
frontend_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
frontend_1  | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
frontend_1  | 	at java.lang.Thread.run(Thread.java:748)
frontend_1  | Caused by: java.sql.SQLException: Unable to load authentication plugin 'caching_sha2_password'.
frontend_1  | 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:925)
frontend_1  | 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:922)
frontend_1  | 	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1769)
frontend_1  | 	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1288)
frontend_1  | 	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2506)
frontend_1  | 	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2539)
frontend_1  | 	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2321)
frontend_1  | 	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:832)
frontend_1  | 	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:46)
frontend_1  | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
frontend_1  | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
frontend_1  | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
frontend_1  | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
frontend_1  | 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
frontend_1  | 	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:417)
frontend_1  | 	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:344)
frontend_1  | 	at org.apache.tomcat.dbcp.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:52)
frontend_1  | 	at org.apache.tomcat.dbcp.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:279)
frontend_1  | 	at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:2356)
frontend_1  | 	at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:2342)
frontend_1  | 	... 25 more
frontend_1  | 
frontend_1  | 13-Aug-2018 19:02:27.482 SEVERE [http-nio-8080-exec-2] org.jetbrains.webdemo.servlet.KotlinHttpServlet.init FATAL ERROR: Initialisation of java core environment failed, server didn't start
frontend_1  |  org.jetbrains.webdemo.database.DatabaseOperationException: Can't create tasks list
frontend_1  | 	at org.jetbrains.webdemo.database.MySqlConnector.createTaskList(MySqlConnector.java:92)
frontend_1  | 	at org.jetbrains.webdemo.servlet.KotlinHttpServlet.init(KotlinHttpServlet.java:69)
frontend_1  | 	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1144)
frontend_1  | 	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1091)
frontend_1  | 	at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:773)
frontend_1  | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:133)
frontend_1  | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
frontend_1  | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
frontend_1  | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
frontend_1  | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
frontend_1  | 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
frontend_1  | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
frontend_1  | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
frontend_1  | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
frontend_1  | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
frontend_1  | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800)
frontend_1  | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471)
frontend_1  | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
frontend_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
frontend_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
frontend_1  | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
frontend_1  | 	at java.lang.Thread.run(Thread.java:748)
frontend_1  | Caused by: java.sql.SQLException: Cannot create PoolableConnectionFactory (Unable to load authentication plugin 'caching_sha2_password'.)
frontend_1  | 	at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:2346)
frontend_1  | 	at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:2072)
frontend_1  | 	at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:1525)
frontend_1  | 	at org.jetbrains.webdemo.database.MySqlConnector.createTaskList(MySqlConnector.java:76)
frontend_1  | 	... 21 more
frontend_1  | Caused by: java.sql.SQLException: Unable to load authentication plugin 'caching_sha2_password'.
frontend_1  | 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:925)
frontend_1  | 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:922)
frontend_1  | 	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1769)
frontend_1  | 	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1288)
frontend_1  | 	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2506)
frontend_1  | 	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2539)
frontend_1  | 	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2321)
frontend_1  | 	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:832)
frontend_1  | 	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:46)
frontend_1  | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
frontend_1  | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
frontend_1  | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
frontend_1  | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
frontend_1  | 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
frontend_1  | 	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:417)
frontend_1  | 	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:344)
frontend_1  | 	at org.apache.tomcat.dbcp.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:52)
frontend_1  | 	at org.apache.tomcat.dbcp.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:279)
frontend_1  | 	at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:2356)
frontend_1  | 	at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:2342)
frontend_1  | 	... 24 more
frontend_1  | 
frontend_1  | 13-Aug-2018 19:02:27.494 INFO [http-nio-8080-exec-3] accessLogger.logRequestInfo frontend sessionId=1CCBCD0B335BFD3DF5D9AC47E0DBBD9B requestType=GET_RESOURCE status=200 time=5 request=/kotlinServer?type=getUserName
frontend_1  | 13-Aug-2018 19:02:27.509 SEVERE [http-nio-8080-exec-5] exceptionLogger.writeExceptionToExceptionAnalyzer   
frontend_1  |  java.sql.SQLException: Cannot create PoolableConnectionFactory (Unable to load authentication plugin 'caching_sha2_password'.)
frontend_1  | 	at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:2346)
frontend_1  | 	at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:2072)
frontend_1  | 	at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:1525)
frontend_1  | 	at org.jetbrains.webdemo.database.MySqlConnector.getUserTaskStatuses(MySqlConnector.java:786)
frontend_1  | 	at org.jetbrains.webdemo.sessions.MyHttpSession.sendExamplesList(MyHttpSession.java:310)
frontend_1  | 	at org.jetbrains.webdemo.sessions.MyHttpSession.handle(MyHttpSession.java:58)
frontend_1  | 	at org.jetbrains.webdemo.handlers.ServerHandler.handle(ServerHandler.java:87)
frontend_1  | 	at org.jetbrains.webdemo.servlet.KotlinHttpServlet.service(KotlinHttpServlet.java:125)
frontend_1  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
frontend_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
frontend_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
frontend_1  | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
frontend_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
frontend_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
frontend_1  | 	at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
frontend_1  | 	at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
frontend_1  | 	at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
frontend_1  | 	at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:389)
frontend_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
frontend_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
frontend_1  | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
frontend_1  | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
frontend_1  | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
frontend_1  | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
frontend_1  | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
frontend_1  | 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
frontend_1  | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
frontend_1  | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
frontend_1  | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
frontend_1  | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
frontend_1  | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800)
frontend_1  | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471)
frontend_1  | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
frontend_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
frontend_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
frontend_1  | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
frontend_1  | 	at java.lang.Thread.run(Thread.java:748)
frontend_1  | Caused by: java.sql.SQLException: Unable to load authentication plugin 'caching_sha2_password'.
frontend_1  | 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:925)
frontend_1  | 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:922)
frontend_1  | 	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1769)
frontend_1  | 	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1288)
frontend_1  | 	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2506)
frontend_1  | 	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2539)
frontend_1  | 	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2321)
frontend_1  | 	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:832)
frontend_1  | 	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:46)
frontend_1  | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
frontend_1  | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
frontend_1  | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
frontend_1  | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
frontend_1  | 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
frontend_1  | 	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:417)
frontend_1  | 	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:344)
frontend_1  | 	at org.apache.tomcat.dbcp.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:52)
frontend_1  | 	at org.apache.tomcat.dbcp.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:279)
frontend_1  | 	at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:2356)
frontend_1  | 	at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:2342)
frontend_1  | 	... 36 more
frontend_1  | 

```

will file this in yourtrack in a minute

**Comment by AlexanderPrendota** [comment]
Unfortunately It's not a full solution :(

**Comment by ligi** [comment]
Hm - I think it is a full solution for the problem for KT-25891 - before adding the character encoding parameter I get:

```
frontend_1  | Caused by: java.lang.NullPointerException
frontend_1  | 	at com.mysql.jdbc.ConnectionImpl.getServerCharacterEncoding(ConnectionImpl.java:3307)
frontend_1  | 	at com.mysql.jdbc.MysqlIO.sendConnectionAttributes(MysqlIO.java:1985)
frontend_1  | 	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1911)
frontend_1  | 	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1288)
frontend_1  | 	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2506)
frontend_1  | 	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2539)
frontend_1  | 	... 50 more
frontend_1  | 
```

without it - I do not get this error - so it looks very much like a solution for *this* problem to me.

**Comment by alexbezhan** [comment]
It seems that the issue is with MySQL version. 

I don't know how docker works, but I'm also trying to get this project up and see, that it is getting the latest version of MySQL(I suppose), which is `8.0.12` for me at the moment. 
But [MySQL renamed their authentication plugin in `8.0.4`](https://stackoverflow.com/questions/50387952/how-to-resolve-unable-to-load-authentication-plugin-caching-sha2-password-issu). So the fix should be to set explicit MySQL version to something smalelr than `before 8.0.4` or somehow run fix suggested on SO page.

**Comment by AlexanderPrendota** [comment]
Hi! This is a new patch to start WEB-DEMO without DB: 
[drop_db_env.patch.zip](https://github.com/JetBrains/kotlin-web-demo/files/2361113/drop_db_env.patch.zip)

I hope It helps. Thanks.

**Comment by AlexanderPrendota** [comment]
@alexbezhan Thanks ^__^

**Pull request closed without merging**
