### PR TITLE
Create lgtm.yml

### PR DESCRIPTION
**Pull request by JLLeitschuh**
Add support for LGTM build linting

Test:
https://lgtm.com/logs/5effb78cc65d8e1eae54bcbb3b6291244a439101/lang:java

### CODE REVIEW

**Comment by AlexanderPrendota** [comment]
@JLLeitschuh Hello! Thanks for the feedback. Why not GH actions or Travis?

**Comment by JLLeitschuh** [comment]
Hi @AlexanderPrendota!

This is totally different from GitHub Actions or Travis. LGTM is a static code analysis tool. It's made by Semmle which was recently purchased by GitHub.

https://github.blog/2019-09-18-github-welcomes-semmle/

**Comment by AlexanderPrendota** [comment]
Hello @JLLeitschuh . Thanks for helping us =). 

Well, okay. Probably we need a badge from [shields](https://img.shields.io).

What do you use kotlin-web-demo for? If you need to compile kotlin code I would suggest you use another [server](https://github.com/AlexanderPrendota/kotlin-compiler-server). it has a lot of tests and uses an open repository to download kotlin dependencies. (currently, kotlin-web-demo uses a private repository).

**Comment by JLLeitschuh** [comment]
@AlexanderPrendota I'm a security researcher that has been finding vulnerabilities in open source software and (on occasion) YouTrack and TeamCity. I like working with your security team.

I'm using LGTM to find common vulnerabilities in OSS and so scanning this project which you use to run the Kotlin online demos gives me the opportunity to find and potentially report vuns that it holds.

**Comment by AlexanderPrendota** [comment]
@JLLeitschuh Hi, okay. Will merge. 
I'm going to migrate all runnable kotlin snippets to the [new server](https://github.com/AlexanderPrendota/kotlin-compiler-server). Shall I add almost the same file?

**Comment by JLLeitschuh** [comment]
Hi @AlexanderPrendota,
Unfortunately, at this time, LGTM only supports Java source files (of the JVM languages).

The best way to make LGTM work on any repository 'out-of-the-box' is to make it so that `./gradlew classes testClasses` runs for the repository on first checkout without any additional configuration.

The reason that the `.lgtm.yml` file was required here was because this repository has a prerequisite before compilation is possible.

**Pull request merged**
